name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build and zip chrome version
        run: bun run zip

      - name: Build and zip firefox version
        run: bun run zip:firefox

      - name: Rename artifacts
        run: |
          cp .output/*-chrome.zip chrome.zip
          cp .output/*-firefox.zip firefox.zip
          cp .output/*-sources.zip sources.zip

      - name: Upload to Firefox Addons
        uses: cardinalby/webext-buildtools-firefox-addons-action@v1
        with:
          zipFilePath: firefox.zip
          sourcesZipFilePath: sources.zip
          extensionId: ${{ secrets.FIREFOX_EXTENSION_ID }}
          jwtIssuer: ${{ secrets.FF_JWT_ISSUER }}
          jwtSecret: ${{ secrets.FF_JWT_SECRET }}

      - name: Upload to Chrome Web Store
        uses: mnao305/chrome-extension-upload@v5.0.0
        with:
          extension-id: ${{ secrets.CHROME_EXTENSION_ID }}
          file-path: chrome.zip
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
